#!/usr/bin/env python3
"""
FILE11F — FEATURE-GENERATION SOURCE-SHIFT / DEBIASING SENSITIVITY
=================================================================

Purpose
-------
Fast go/no-go diagnostic for a potential feature-generation source artifact in
the known-AMR representation.

Development known-AMR rows were generated through two branches:
  1) NCBI Pathogen Detection precomputed AMR genotypes
  2) local AMRFinderPlus completion for 382 unresolved genomes

External E2 was called locally with AMRFinderPlus. FILE11F asks:
  - Can the 668-feature vector predict which development branch generated it?
  - Which features carry the strongest source association?
  - Do source-associated features overlap high-impact resistance-model features?
  - Does a DEVELOPMENT-ONLY source-debiased model change external E2 behavior?
  - Does training only on the source-matched local branch change E2 behavior?

IMPORTANT
---------
This is a POST-HOC EXPLORATORY SENSITIVITY ANALYSIS designed after FILE11C E2
results were known. It MUST NOT replace the frozen FILE11C primary external
result and MUST NOT be described as confirmatory.

No E2 labels are used to:
  - define source markers,
  - select features,
  - tune C,
  - tune threshold,
  - select a model.

All pre-specified sensitivity models are reported. No "best model" is selected.

Primary fixed source-marker rule
--------------------------------
A feature is a source marker iff, in the 4,227 development genomes:
  - Benjamini-Hochberg q <= 0.01 for NCBI-vs-local Fisher exact test, AND
  - absolute prevalence difference >= 0.20.

The source-debiased model removes ALL features meeting that rule, then fits the
same locked LogisticRegression specification as FILE11C:
  C=1.0, solver=liblinear, class_weight=None, max_iter=3000,
  random_state=20260920, threshold=0.5.

Pre-specified sensitivity models
--------------------------------
  frozen_original
      FILE11C predictions; never refit.

  source_debiased_full
      All 4,227 development genomes; source-marker features removed.

  local_source_only
      Development genomes generated by local AMRFinder branch only;
      all 668 frozen features retained.

  ncbi_source_only
      Development genomes generated by NCBI-precomputed branch only;
      all 668 frozen features retained.

Caveat
------
The source branch is NOT randomized. Source associations may reflect technical
differences, population/lineage differences, calendar/accession differences, or
a mixture. FILE11F diagnoses source separability; it cannot by itself prove
causality.

Typical run
-----------
python scripts/file11f_feature_source_shift.py \
  --project-root /mnt/c/Users/ASUS/Desktop/AMR-Genome-ML \
  --bootstrap-replicates 2000

Optional if automatic development-label discovery fails:
  --development-labels /path/to/file07_or_phenotype_table.csv

Outputs
-------
data/external_validation/ncbi_pathogen_detection/file11f/
  file11f_source_feature_associations.csv
  file11f_source_classifier_cv.csv
  file11f_source_outcome_confounding.csv
  file11f_source_marker_overlap.csv
  file11f_internal_cv_sensitivity.csv
  file11f_external_sensitivity_metrics.csv
  file11f_external_paired_cluster_bootstrap.csv
  file11f_external_sensitivity_predictions.csv
  file11f_analysis_design.json
  file11f_label_source_audit.csv

checkpoints/external_validation_file11f/
  file11f_final_summary.json
  file11f_last_failure.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import signal
import tempfile
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from scipy.stats import fisher_exact
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    log_loss,
    matthews_corrcoef,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold

try:
    from sklearn.model_selection import StratifiedGroupKFold
except Exception:
    StratifiedGroupKFold = None


VERSION = "1.0.5"

EXPECTED_DEV_N = 4227
EXPECTED_DEV_R = 1601
EXPECTED_DEV_S = 2626
EXPECTED_FEATURES = 668
EXPECTED_LOCAL_MANIFEST = 382

EXPECTED_E2_N = 525
EXPECTED_E2_R = 163
EXPECTED_E2_S = 362
EXPECTED_ERD_GROUPS = 289

MODEL_C = 1.0
MODEL_SOLVER = "liblinear"
MODEL_MAX_ITER = 3000
MODEL_RANDOM_STATE = 20260920
THRESHOLD = 0.5

SOURCE_MARKER_Q = 0.01
SOURCE_MARKER_ABS_SHIFT = 0.20

RANDOM_SEED = 20260922
STOP = False


# =============================================================================
# Generic utilities
# =============================================================================

def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def sha256_file(path: Path, block: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            b = fh.read(block)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def atomic_json(path: Path, obj: Any) -> None:
    atomic_text(path, json.dumps(obj, indent=2, sort_keys=True, default=str) + "\n")


def atomic_csv(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp.csv", dir=path.parent)
    os.close(fd)
    p = Path(tmp)
    try:
        df.to_csv(p, index=False)
        with p.open("rb") as fh:
            os.fsync(fh.fileno())
        os.replace(p, path)
    except Exception:
        p.unlink(missing_ok=True)
        raise


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"Missing {label}: {path}")


def acquire_lock(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        try:
            old = json.loads(path.read_text(encoding="utf-8"))
            pid = int(old.get("pid", -1))
        except Exception:
            pid = -1
        if pid > 0 and Path(f"/proc/{pid}").exists():
            raise RuntimeError(f"Active FILE11F lock exists: {path} (PID {pid})")
        path.unlink(missing_ok=True)
    atomic_json(path, {"pid": os.getpid(), "started_utc": utc_now(), "version": VERSION})


def signal_handler(_signum, _frame) -> None:
    global STOP
    STOP = True


def norm_id(x: Any) -> str:
    if pd.isna(x):
        return ""
    return str(x).strip()


def safe_div(a: float, b: float) -> float:
    return float(a / b) if b else float("nan")


def bh_fdr(pvals: np.ndarray) -> np.ndarray:
    p = np.asarray(pvals, dtype=float)
    out = np.full(len(p), np.nan, dtype=float)
    good = np.isfinite(p)
    if not np.any(good):
        return out

    vals = p[good]
    order = np.argsort(vals)
    ranked = vals[order]
    n = len(ranked)
    q = ranked * n / np.arange(1, n + 1)
    q = np.minimum.accumulate(q[::-1])[::-1]
    q = np.clip(q, 0.0, 1.0)

    restored = np.empty(n, dtype=float)
    restored[order] = q
    out[np.flatnonzero(good)] = restored
    return out


def json_float(x: Any) -> float | None:
    try:
        v = float(x)
    except Exception:
        return None
    return v if np.isfinite(v) else None


# =============================================================================
# Binary labels / table discovery
# =============================================================================

ID_HINTS = (
    "genome id",
    "genome_id",
    "genome",
    "assembly accession",
    "assembly_accession",
    "asm_acc",
    "target_acc",
    "accession",
)

LABEL_HINTS = (
    "label_binary",
    "phenotype_binary",
    "binary_label",
    "meropenem",
    "phenotype",
    "label",
    "resistance",
)

MLST_HINTS = (
    "mlst",
    "sequence_type",
    "sequence type",
    "st",
)


def map_binary_series(s: pd.Series) -> pd.Series | None:
    raw = s.copy()

    numeric = pd.to_numeric(raw, errors="coerce")
    nonmissing = numeric.dropna()
    if len(nonmissing) and set(nonmissing.unique()).issubset({0, 1}):
        return numeric.astype("Float64")

    text = raw.astype(str).str.strip().str.upper()
    mapper = {
        "R": 1,
        "RESISTANT": 1,
        "RESISTANCE": 1,
        "1": 1,
        "1.0": 1,
        "S": 0,
        "SUSCEPTIBLE": 0,
        "SUSCEPTIBILITY": 0,
        "0": 0,
        "0.0": 0,
    }
    mapped = text.map(mapper)
    original_not_missing = ~raw.isna()
    if original_not_missing.sum() and mapped[original_not_missing].notna().all():
        return mapped.astype("Float64")

    return None


def likely_id_columns(columns: list[str]) -> list[str]:
    out = []
    for c in columns:
        lc = c.strip().lower()
        score = 0
        for i, hint in enumerate(ID_HINTS):
            if lc == hint:
                score += 100 - i
            elif hint in lc:
                score += 10
        if score:
            out.append((score, c))
    return [c for _, c in sorted(out, reverse=True)]


def likely_label_columns(columns: list[str]) -> list[str]:
    out = []
    for c in columns:
        lc = c.strip().lower()
        score = 0
        for i, hint in enumerate(LABEL_HINTS):
            if lc == hint:
                score += 100 - i
            elif hint in lc:
                score += 10
        if score:
            out.append((score, c))
    return [c for _, c in sorted(out, reverse=True)]


def find_mlst_column(columns: list[str]) -> str | None:
    exact_priority = ["MLST", "mlst", "sequence_type", "Sequence Type", "ST", "st"]
    for c in exact_priority:
        if c in columns:
            return c

    for c in columns:
        lc = c.strip().lower()
        if "mlst" in lc or "sequence_type" in lc or "sequence type" in lc:
            return c
    return None


def read_table(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path, low_memory=False)
    if suffix in {".tsv", ".txt"}:
        return pd.read_csv(path, sep="\t", low_memory=False)
    if suffix == ".parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported table format: {path}")


def candidate_label_files(root: Path) -> list[Path]:
    preferred = []
    patterns = [
        "**/*file07*.csv",
        "**/*fold*.csv",
        "**/*split*.csv",
        "**/*cohort*.csv",
        "**/*phenotype*.csv",
        "**/*meropenem*.csv",
        "**/*file07*.tsv",
        "**/*fold*.tsv",
        "**/*split*.tsv",
        "**/*cohort*.tsv",
        "**/*phenotype*.tsv",
        "**/*file07*.parquet",
        "**/*fold*.parquet",
        "**/*cohort*.parquet",
    ]
    seen = set()
    for pattern in patterns:
        for p in root.glob(pattern):
            if not p.is_file():
                continue
            rp = p.resolve()
            if rp in seen:
                continue
            seen.add(rp)
            # Do not inspect very large feature matrices or FILE11 external outputs.
            try:
                size = p.stat().st_size
            except OSError:
                continue
            if size > 120 * 1024 * 1024:
                continue
            lname = p.name.lower()
            if any(x in lname for x in ("unitig", "pangenome", "known_amr_final", "file11c_external")):
                continue
            preferred.append(p)

    def rank(p: Path) -> tuple:
        name = p.name.lower()
        path = str(p).lower()
        return (
            0 if "file07" in name else 1,
            0 if "common" in name or "cohort" in name else 1,
            0 if "fold" in name or "split" in name else 1,
            0 if "validation" in path else 1,
            len(str(p)),
        )

    return sorted(preferred, key=rank)


def evaluate_label_candidate(
    path: Path,
    x_ids: set[str],
) -> tuple[pd.DataFrame, str, str, str | None] | None:
    try:
        df = read_table(path)
    except Exception:
        return None
    if len(df) < EXPECTED_DEV_N:
        return None

    id_cols = likely_id_columns(list(df.columns))
    label_cols = likely_label_columns(list(df.columns))

    # If label hints miss, inspect low-cardinality columns.
    if not label_cols:
        for c in df.columns:
            if df[c].nunique(dropna=True) <= 5:
                label_cols.append(c)

    for id_col in id_cols[:5]:
        ids = df[id_col].map(norm_id)
        overlap = ids.isin(x_ids)
        if int(overlap.sum()) < EXPECTED_DEV_N:
            continue

        for label_col in label_cols[:15]:
            if label_col == id_col:
                continue
            mapped = map_binary_series(df[label_col])
            if mapped is None:
                continue

            tmp = pd.DataFrame(
                {
                    "genome_id": ids,
                    "label_binary": mapped,
                }
            )
            mlst_col = find_mlst_column(list(df.columns))
            if mlst_col is not None:
                tmp["MLST"] = df[mlst_col]

            tmp = tmp[tmp["genome_id"].isin(x_ids)].copy()
            tmp = tmp[tmp["label_binary"].notna()].copy()
            if tmp.empty:
                continue

            # Require duplicate IDs to have consistent labels.
            inconsistent = (
                tmp.groupby("genome_id")["label_binary"].nunique(dropna=True) > 1
            )
            if inconsistent.any():
                continue

            tmp = tmp.drop_duplicates("genome_id", keep="first")
            if len(tmp) != EXPECTED_DEV_N:
                continue

            tmp["label_binary"] = tmp["label_binary"].astype(int)
            r = int(tmp["label_binary"].sum())
            s = int(len(tmp) - r)
            if r == EXPECTED_DEV_R and s == EXPECTED_DEV_S:
                return tmp, id_col, label_col, mlst_col

    return None



def load_canonical_file07_common_cohort(
    root: Path,
    x_ids: set[str],
) -> tuple[pd.DataFrame, dict[str, Any]] | None:
    """
    Prefer the locked File07 cohort schema when available:
      Genome ID, Phenotype, y, MLST

    This avoids heuristic label discovery and uses the exact development cohort
    that generated FILE08/FILE09. The binary outcome is taken from `y`; the
    Phenotype column is cross-checked against y.
    """
    path = root / "data/processed/file07_common_cohort.csv"
    if not path.is_file():
        return None

    # Force Genome ID to string to avoid numeric coercion changing identifiers.
    df = pd.read_csv(path, dtype={"Genome ID": str}, low_memory=False)

    required = {"Genome ID", "Phenotype", "y", "MLST"}
    if not required.issubset(df.columns):
        return None

    if len(df) != EXPECTED_DEV_N:
        raise RuntimeError(
            f"Canonical File07 common cohort has n={len(df)}, "
            f"expected {EXPECTED_DEV_N}."
        )

    ids = df["Genome ID"].map(norm_id)
    if ids.duplicated().any():
        dup = ids[ids.duplicated(keep=False)].unique()[:20].tolist()
        raise RuntimeError(
            f"Canonical File07 common cohort has duplicate Genome IDs: {dup}"
        )

    y = pd.to_numeric(df["y"], errors="raise").astype(int)
    if not set(y.unique()).issubset({0, 1}):
        raise RuntimeError("Canonical File07 `y` is not binary 0/1.")

    pheno = df["Phenotype"].astype(str).str.strip().str.upper()
    pheno_y = pheno.map({"S": 0, "R": 1})
    if pheno_y.isna().any():
        bad = sorted(pheno[pheno_y.isna()].unique())[:20]
        raise RuntimeError(
            f"Canonical File07 Phenotype has unexpected values: {bad}"
        )
    if not np.array_equal(pheno_y.to_numpy(dtype=int), y.to_numpy(dtype=int)):
        raise RuntimeError("Canonical File07 Phenotype and y columns disagree.")

    r = int(y.sum())
    s = int(len(y) - r)
    if r != EXPECTED_DEV_R or s != EXPECTED_DEV_S:
        raise RuntimeError(
            f"Canonical File07 outcome signature mismatch: n={len(y)}, R={r}, S={s}"
        )

    overlap_mask = ids.isin(x_ids)
    overlap_n = int(overlap_mask.sum())
    missing_ids = sorted(set(ids) - x_ids)
    if overlap_n != EXPECTED_DEV_N:
        raise RuntimeError(
            "Canonical File07 development IDs are not fully represented in the "
            f"raw known-AMR matrix: overlap={overlap_n}/{EXPECTED_DEV_N}, "
            f"missing={len(missing_ids)}, examples={missing_ids[:20]}"
        )

    labels = pd.DataFrame(
        {
            "genome_id": ids,
            "label_binary": y,
            "MLST": df["MLST"],
        }
    )

    meta = {
        "selected_path": str(path),
        "id_column": "Genome ID",
        "label_column": "y",
        "phenotype_crosscheck_column": "Phenotype",
        "mlst_column": "MLST",
        "selection_mode": "canonical_file07_common_cohort",
        "audit": [
            {
                "path": str(path),
                "matched_exact_development_signature": True,
                "n": len(df),
                "R": r,
                "S": s,
                "ID_overlap_with_known_AMR": overlap_n,
            }
        ],
    }
    return labels, meta


def discover_development_labels(
    root: Path,
    x_ids: set[str],
    explicit: Path | None,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    candidates = [explicit] if explicit is not None else candidate_label_files(root)

    audit_rows = []
    for i, path in enumerate(candidates, start=1):
        if path is None or not path.is_file():
            continue
        log(f"[PROGRESS] label discovery {i}/{len(candidates)} | {path}")
        result = evaluate_label_candidate(path, x_ids)
        audit_rows.append(
            {
                "path": str(path),
                "matched_exact_development_signature": result is not None,
            }
        )
        if result is not None:
            labels, id_col, label_col, mlst_col = result
            meta = {
                "selected_path": str(path),
                "id_column": id_col,
                "label_column": label_col,
                "mlst_column": mlst_col,
                "audit": audit_rows,
            }
            return labels, meta

    msg = (
        "Could not automatically locate a development label table with exactly "
        f"n={EXPECTED_DEV_N}, R={EXPECTED_DEV_R}, S={EXPECTED_DEV_S}. "
        "Rerun with --development-labels /path/to/File07_or_phenotype_table.csv"
    )
    raise RuntimeError(msg)


# =============================================================================
# Matrix/model helpers
# =============================================================================

def detect_id_column(df: pd.DataFrame, feature_names: list[str]) -> str:
    nonfeatures = [c for c in df.columns if c not in set(feature_names)]
    likely = likely_id_columns(nonfeatures)
    if likely:
        return likely[0]
    if len(nonfeatures) == 1:
        return nonfeatures[0]
    raise RuntimeError(
        f"Cannot identify genome-ID column. Non-feature columns={nonfeatures[:20]}"
    )


def new_outcome_model() -> LogisticRegression:
    return LogisticRegression(
        C=MODEL_C,
        solver=MODEL_SOLVER,
        class_weight=None,
        max_iter=MODEL_MAX_ITER,
        random_state=MODEL_RANDOM_STATE,
    )


def new_source_model() -> LogisticRegression:
    return LogisticRegression(
        C=1.0,
        solver="liblinear",
        class_weight="balanced",
        max_iter=3000,
        random_state=RANDOM_SEED,
    )


def positive_probability(model: LogisticRegression, X: np.ndarray) -> np.ndarray:
    classes = list(model.classes_)
    if 1 not in classes:
        raise RuntimeError(f"Model classes do not include positive class 1: {classes}")
    j = classes.index(1)
    return model.predict_proba(X)[:, j]


def extract_frozen_estimator(artifact: Any) -> Any:
    if hasattr(artifact, "predict_proba"):
        return artifact
    if isinstance(artifact, dict):
        for key in ("model", "estimator", "classifier", "clf"):
            obj = artifact.get(key)
            if hasattr(obj, "predict_proba"):
                return obj
    return None


# =============================================================================
# Metrics
# =============================================================================

def metric_bundle(y: np.ndarray, p: np.ndarray, pred: np.ndarray) -> dict[str, float]:
    y = np.asarray(y, dtype=np.uint8)
    p = np.asarray(p, dtype=float)
    pred = np.asarray(pred, dtype=np.uint8)

    tn, fp, fn, tp = confusion_matrix(y, pred, labels=[0, 1]).ravel()
    return {
        "n": int(len(y)),
        "R": int(y.sum()),
        "S": int((1 - y).sum()),
        "roc_auc": (
            float(roc_auc_score(y, p))
            if len(np.unique(y)) == 2
            else float("nan")
        ),
        "average_precision": (
            float(average_precision_score(y, p))
            if int(y.sum()) > 0
            else float("nan")
        ),
        "accuracy": float(accuracy_score(y, pred)),
        "balanced_accuracy": (
            float(balanced_accuracy_score(y, pred))
            if len(np.unique(y)) == 2
            else float("nan")
        ),
        "sensitivity": safe_div(tp, tp + fn),
        "specificity": safe_div(tn, tn + fp),
        "f1": float(f1_score(y, pred, zero_division=0)),
        "mcc": float(matthews_corrcoef(y, pred)),
        "brier": float(brier_score_loss(y, p)),
        "log_loss": float(log_loss(y, np.clip(p, 1e-15, 1 - 1e-15), labels=[0, 1])),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }


# =============================================================================
# Source-feature associations
# =============================================================================

def source_feature_associations(
    X: pd.DataFrame,
    source_local: np.ndarray,
    feature_names: list[str],
    resistance_coefficients: pd.DataFrame,
) -> pd.DataFrame:
    local = np.asarray(source_local, dtype=bool)
    ncbi = ~local

    coef_map = (
        resistance_coefficients.set_index("feature")["coefficient"].to_dict()
        if {"feature", "coefficient"}.issubset(resistance_coefficients.columns)
        else {}
    )

    rows = []
    arr = X[feature_names].to_numpy(dtype=np.uint8)

    for j, feature in enumerate(feature_names):
        present = arr[:, j].astype(bool)

        a = int(np.sum(present & local))
        b = int(np.sum((~present) & local))
        c = int(np.sum(present & ncbi))
        d = int(np.sum((~present) & ncbi))

        p_local = safe_div(a, a + b)
        p_ncbi = safe_div(c, c + d)
        delta = p_local - p_ncbi

        try:
            odds, pval = fisher_exact([[a, b], [c, d]], alternative="two-sided")
            odds = float(odds)
            pval = float(pval)
        except Exception:
            odds, pval = float("nan"), float("nan")

        coef = float(coef_map.get(feature, np.nan))
        rows.append(
            {
                "feature": feature,
                "local_present": a,
                "local_absent": b,
                "ncbi_present": c,
                "ncbi_absent": d,
                "local_prevalence": p_local,
                "ncbi_prevalence": p_ncbi,
                "local_minus_ncbi_prevalence": delta,
                "absolute_prevalence_shift": abs(delta),
                "source_odds_ratio_local_vs_ncbi": odds,
                "source_fisher_p": pval,
                "resistance_model_coefficient": coef,
                "abs_resistance_model_coefficient": abs(coef) if np.isfinite(coef) else np.nan,
            }
        )

    out = pd.DataFrame(rows)
    out["source_fisher_q_BH"] = bh_fdr(out["source_fisher_p"].to_numpy())
    out["primary_source_marker"] = (
        (out["source_fisher_q_BH"] <= SOURCE_MARKER_Q)
        & (out["absolute_prevalence_shift"] >= SOURCE_MARKER_ABS_SHIFT)
    )
    out["coefficient_weighted_abs_source_shift"] = (
        out["abs_resistance_model_coefficient"]
        * out["absolute_prevalence_shift"]
    )

    return out.sort_values(
        ["primary_source_marker", "absolute_prevalence_shift", "source_fisher_q_BH"],
        ascending=[False, False, True],
        na_position="last",
    )


# =============================================================================
# Source classifier CV
# =============================================================================

def source_classifier_cv(
    X: pd.DataFrame,
    source_local: np.ndarray,
    feature_names: list[str],
    mlst: pd.Series | None,
) -> pd.DataFrame:
    Xn = X[feature_names].to_numpy(dtype=np.float64)
    y = np.asarray(source_local, dtype=np.uint8)

    rows = []

    def run_scheme(name: str, splits):
        oof = np.full(len(y), np.nan, dtype=float)
        fold_ids = np.full(len(y), -1, dtype=int)

        for fold, (tr, te) in enumerate(splits, start=1):
            if STOP:
                raise KeyboardInterrupt
            if len(np.unique(y[tr])) < 2 or len(np.unique(y[te])) < 2:
                raise RuntimeError(
                    f"{name} source-CV fold {fold} lacks both source classes."
                )
            model = new_source_model()
            model.fit(Xn[tr], y[tr])
            oof[te] = positive_probability(model, Xn[te])
            fold_ids[te] = fold

        if np.isnan(oof).any() or (fold_ids < 0).any():
            raise RuntimeError(f"Incomplete OOF source predictions for {name}.")

        pred = (oof >= 0.5).astype(np.uint8)
        tn, fp, fn, tp = confusion_matrix(y, pred, labels=[0, 1]).ravel()

        rows.append(
            {
                "scheme": name,
                "n": len(y),
                "local_n": int(y.sum()),
                "ncbi_n": int((1 - y).sum()),
                "roc_auc": float(roc_auc_score(y, oof)),
                "average_precision": float(average_precision_score(y, oof)),
                "balanced_accuracy": float(balanced_accuracy_score(y, pred)),
                "mcc": float(matthews_corrcoef(y, pred)),
                "sensitivity_local": safe_div(tp, tp + fn),
                "specificity_ncbi": safe_div(tn, tn + fp),
            }
        )

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)
    run_scheme("stratified_random_5fold", skf.split(Xn, y))

    if mlst is not None and StratifiedGroupKFold is not None:
        # MLST can contain a mixture of numeric ST values and unresolved strings.
        # Normalize every entry explicitly to a pure string array BEFORE grouping.
        # Avoid np.unique(object), which sorts and can fail when mixed float/str
        # objects survive pandas conversion.
        groups = np.asarray(
            [
                "UNRESOLVED"
                if pd.isna(v) or str(v).strip() == "" or str(v).strip().lower() == "nan"
                else str(v).strip()
                for v in mlst.tolist()
            ],
            dtype=str,
        )
        if len(set(groups.tolist())) >= 5:
            try:
                sgkf = StratifiedGroupKFold(
                    n_splits=5,
                    shuffle=True,
                    random_state=RANDOM_SEED,
                )
                run_scheme("MLST_grouped_5fold", sgkf.split(Xn, y, groups=groups))
            except Exception as exc:
                rows.append(
                    {
                        "scheme": "MLST_grouped_5fold_SKIPPED",
                        "n": len(y),
                        "local_n": int(y.sum()),
                        "ncbi_n": int((1 - y).sum()),
                        "roc_auc": np.nan,
                        "average_precision": np.nan,
                        "balanced_accuracy": np.nan,
                        "mcc": np.nan,
                        "sensitivity_local": np.nan,
                        "specificity_ncbi": np.nan,
                        "note": str(exc),
                    }
                )

    return pd.DataFrame(rows)


# =============================================================================
# Internal CV for outcome-model sensitivities
# =============================================================================

def internal_cv_model(
    X: pd.DataFrame,
    y: np.ndarray,
    feature_names: list[str],
    subset_mask: np.ndarray,
    model_name: str,
) -> dict[str, Any]:
    idx = np.flatnonzero(subset_mask)
    yy = np.asarray(y, dtype=np.uint8)[idx]
    XX = X.loc[idx, feature_names].to_numpy(dtype=np.float64)

    if len(idx) < 50 or len(np.unique(yy)) < 2:
        return {
            "model": model_name,
            "n": len(idx),
            "R": int(yy.sum()),
            "S": int(len(yy) - yy.sum()),
            "cv_scheme": "stratified_random_5fold",
            "roc_auc": np.nan,
            "average_precision": np.nan,
            "balanced_accuracy": np.nan,
            "mcc": np.nan,
            "note": "Insufficient rows/classes for 5-fold sensitivity CV",
        }

    n_splits = 5
    min_class = min(int(yy.sum()), int((1 - yy).sum()))
    if min_class < 5:
        n_splits = max(2, min_class)

    skf = StratifiedKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=RANDOM_SEED,
    )
    oof = np.full(len(yy), np.nan, dtype=float)

    for tr, te in skf.split(XX, yy):
        m = new_outcome_model()
        m.fit(XX[tr], yy[tr])
        oof[te] = positive_probability(m, XX[te])

    pred = (oof >= THRESHOLD).astype(np.uint8)
    met = metric_bundle(yy, oof, pred)
    return {
        "model": model_name,
        "n": met["n"],
        "R": met["R"],
        "S": met["S"],
        "cv_scheme": f"stratified_random_{n_splits}fold",
        "roc_auc": met["roc_auc"],
        "average_precision": met["average_precision"],
        "balanced_accuracy": met["balanced_accuracy"],
        "mcc": met["mcc"],
        "sensitivity": met["sensitivity"],
        "specificity": met["specificity"],
        "brier": met["brier"],
        "log_loss": met["log_loss"],
    }


# =============================================================================
# External paired cluster bootstrap
# =============================================================================

BOOT_METRICS = (
    "roc_auc",
    "average_precision",
    "balanced_accuracy",
    "mcc",
    "sensitivity",
    "specificity",
    "brier",
    "log_loss",
)


def paired_cluster_bootstrap(
    pred_df: pd.DataFrame,
    method_scores: dict[str, np.ndarray],
    n_boot: int,
    seed: int,
) -> pd.DataFrame:
    y_all = pred_df["label_binary"].to_numpy(dtype=np.uint8)
    erd = pred_df["erd_group"].astype(str).to_numpy()
    unique_groups = np.unique(erd)
    group_idx = {g: np.flatnonzero(erd == g) for g in unique_groups}
    rng = np.random.default_rng(seed)

    comparators = [m for m in method_scores if m != "frozen_original"]
    draws = {
        comp: {metric: [] for metric in BOOT_METRICS}
        for comp in comparators
    }

    point = {}
    for name, p in method_scores.items():
        pr = (np.asarray(p) >= THRESHOLD).astype(np.uint8)
        point[name] = metric_bundle(y_all, p, pr)

    valid = 0
    for b in range(n_boot):
        if STOP:
            raise KeyboardInterrupt

        sampled = rng.choice(unique_groups, size=len(unique_groups), replace=True)
        idx = np.concatenate([group_idx[g] for g in sampled])
        y = y_all[idx]
        if len(np.unique(y)) < 2:
            continue

        base_p = np.asarray(method_scores["frozen_original"])[idx]
        base = metric_bundle(y, base_p, (base_p >= THRESHOLD).astype(np.uint8))

        for comp in comparators:
            cp = np.asarray(method_scores[comp])[idx]
            cm = metric_bundle(y, cp, (cp >= THRESHOLD).astype(np.uint8))
            for metric in BOOT_METRICS:
                if np.isfinite(cm[metric]) and np.isfinite(base[metric]):
                    # comparator minus frozen original
                    draws[comp][metric].append(cm[metric] - base[metric])

        valid += 1
        if b == 0 or (b + 1) % 250 == 0 or b + 1 == n_boot:
            log(f"[PROGRESS] paired ERD bootstrap {b+1}/{n_boot} | valid={valid}")

    rows = []
    for comp in comparators:
        for metric in BOOT_METRICS:
            arr = np.asarray(draws[comp][metric], dtype=float)
            if len(arr) == 0:
                continue
            rows.append(
                {
                    "contrast": f"{comp}_minus_frozen_original",
                    "model": comp,
                    "metric": metric,
                    "point_frozen_original": point["frozen_original"][metric],
                    "point_sensitivity_model": point[comp][metric],
                    "point_delta": point[comp][metric] - point["frozen_original"][metric],
                    "delta_definition": (
                        "sensitivity model minus frozen original; positive favors "
                        "sensitivity model for AUROC/AP/BA/MCC/sensitivity/specificity; "
                        "negative favors sensitivity model for Brier/log_loss"
                    ),
                    "n_boot_requested": n_boot,
                    "n_boot_valid": len(arr),
                    "bootstrap_delta_mean": float(arr.mean()),
                    "ci95_low": float(np.quantile(arr, 0.025)),
                    "ci95_high": float(np.quantile(arr, 0.975)),
                }
            )

    return pd.DataFrame(rows)


# =============================================================================
# Main
# =============================================================================

def main() -> int:
    ap = argparse.ArgumentParser(
        description="FILE11F feature-generation source-shift sensitivity analysis."
    )
    ap.add_argument("--project-root", required=True, type=Path)
    ap.add_argument("--bootstrap-replicates", type=int, default=2000)
    ap.add_argument("--development-labels", type=Path, default=None)
    args = ap.parse_args()

    if args.bootstrap_replicates < 1000:
        raise SystemExit("--bootstrap-replicates must be >=1000")

    root = args.project_root.resolve()
    if args.development_labels is not None:
        args.development_labels = args.development_labels.resolve()

    out_dir = root / "data/external_validation/ncbi_pathogen_detection/file11f"
    ckpt = root / "checkpoints/external_validation_file11f"
    lock_path = ckpt / "file11f.lock"
    failure_path = ckpt / "file11f_last_failure.json"
    final_summary_path = ckpt / "file11f_final_summary.json"

    inputs = {
        "X_known_amr": root / "data/features/known_amr/X_known_amr_final.csv",
        "local_manifest": root
        / "data/features/known_amr/amrfinder_local_completion_manifest.csv",
        "file11c_summary": root
        / "checkpoints/external_validation_file11c/file11c_final_summary.json",
        "file11c_model": root
        / "checkpoints/external_validation_file11c/file11c_final_model.joblib",
        "file11c_predictions": root
        / "data/external_validation/ncbi_pathogen_detection/file11c/file11c_blind_predictions.csv",
        "file11c_X_external": root
        / "data/external_validation/ncbi_pathogen_detection/file11c/file11c_external_known_amr_668.csv",
        "file11c_coefficients": root
        / "data/external_validation/ncbi_pathogen_detection/file11c/file11c_model_coefficients.csv",
        "e2": root
        / "data/external_validation/ncbi_pathogen_detection/final/file11_external_strict_E2_FROZEN.csv",
    }

    outputs = {
        "source_features": out_dir / "file11f_source_feature_associations.csv",
        "source_cv": out_dir / "file11f_source_classifier_cv.csv",
        "source_outcome": out_dir / "file11f_source_outcome_confounding.csv",
        "marker_overlap": out_dir / "file11f_source_marker_overlap.csv",
        "internal_cv": out_dir / "file11f_internal_cv_sensitivity.csv",
        "external_metrics": out_dir / "file11f_external_sensitivity_metrics.csv",
        "external_bootstrap": out_dir / "file11f_external_paired_cluster_bootstrap.csv",
        "external_predictions": out_dir / "file11f_external_sensitivity_predictions.csv",
        "design": out_dir / "file11f_analysis_design.json",
        "label_audit": out_dir / "file11f_label_source_audit.csv",
    }

    out_dir.mkdir(parents=True, exist_ok=True)
    ckpt.mkdir(parents=True, exist_ok=True)
    acquire_lock(lock_path)

    stage = "startup"
    started = time.time()

    try:
        log("=" * 112)
        log("FILE11F — FEATURE-GENERATION SOURCE-SHIFT / DEBIASING SENSITIVITY")
        log("=" * 112)
        log(f"Version       : {VERSION}")
        log(f"Project root  : {root}")
        log(f"Bootstrap     : {args.bootstrap_replicates}")
        log(
            f"Source marker : BH q<={SOURCE_MARKER_Q} AND "
            f"|prevalence shift|>={SOURCE_MARKER_ABS_SHIFT:.2f}"
        )
        log("Mode          : POST-HOC EXPLORATORY — NO E2-GUIDED SELECTION")

        for label, path in inputs.items():
            require_file(path, label)

        # ---------------------------------------------------------------------
        stage = "stage1_integrity"
        log("Stage 1/8 — verify FILE11C freeze and load exact 668-feature schema")

        csum = json.loads(inputs["file11c_summary"].read_text(encoding="utf-8"))
        if csum.get("status") != "PASS_BLIND_EXTERNAL_VALIDATION":
            raise RuntimeError("FILE11C is not PASS_BLIND_EXTERNAL_VALIDATION.")

        hash_checks = {
            "E2": (inputs["e2"], csum["frozen_e2_sha256"]),
            "model": (inputs["file11c_model"], csum["frozen_model_sha256"]),
            "predictions": (
                inputs["file11c_predictions"],
                csum["frozen_prediction_sha256"],
            ),
        }
        for name, (path, expected) in hash_checks.items():
            observed = sha256_file(path)
            if observed != expected:
                raise RuntimeError(
                    f"Frozen {name} hash mismatch: expected={expected}, observed={observed}"
                )

        artifact = joblib.load(inputs["file11c_model"])
        if not isinstance(artifact, dict) or "features" not in artifact:
            raise RuntimeError("Frozen FILE11C model artifact lacks feature schema.")
        feature_names = list(artifact["features"])
        if len(feature_names) != EXPECTED_FEATURES:
            raise RuntimeError(f"Expected 668 features, got {len(feature_names)}")

        frozen_estimator = extract_frozen_estimator(artifact)

        pred_e2 = pd.read_csv(inputs["file11c_predictions"], dtype={"asm_acc": str})
        if (
            len(pred_e2) != EXPECTED_E2_N
            or int(pred_e2["label_binary"].sum()) != EXPECTED_E2_R
            or int((1 - pred_e2["label_binary"]).sum()) != EXPECTED_E2_S
        ):
            raise RuntimeError("Unexpected E2 prediction cohort signature.")
        if pred_e2["erd_group"].nunique() != EXPECTED_ERD_GROUPS:
            raise RuntimeError("Unexpected E2 ERD-group count.")

        p_frozen = pred_e2["probability_R"].to_numpy(dtype=float)
        y_e2 = pred_e2["label_binary"].to_numpy(dtype=np.uint8)
        frozen_metrics = metric_bundle(
            y_e2,
            p_frozen,
            pred_e2["predicted_R"].to_numpy(dtype=np.uint8),
        )
        if abs(frozen_metrics["roc_auc"] - float(csum["metrics"]["roc_auc"])) > 1e-12:
            raise RuntimeError("Frozen FILE11C AUROC reproduction failed.")

        log(
            f"[PROGRESS] freeze PASS | E2 AUROC={frozen_metrics['roc_auc']:.4f} | "
            f"prediction_sha256={csum['frozen_prediction_sha256']}"
        )

        # ---------------------------------------------------------------------
        stage = "stage2_source_reconstruction"
        log("Stage 2/8 — reconstruct development source labels and outcome labels")

        # Genome IDs such as "573.12780" MUST be read as strings. Reading the
        # ID column through pandas numeric inference would silently coerce it to
        # "573.1278", destroying exact NCBI Pathogen Detection identifiers and
        # creating both false missing IDs and false duplicates.
        x_header = pd.read_csv(inputs["X_known_amr"], nrows=0)
        id_col = detect_id_column(x_header, feature_names)
        Xall = pd.read_csv(
            inputs["X_known_amr"],
            dtype={id_col: str},
            low_memory=False,
        )
        Xall[id_col] = Xall[id_col].map(norm_id)

        missing_features = [f for f in feature_names if f not in Xall.columns]
        if missing_features:
            raise RuntimeError(
                f"Known-AMR matrix missing frozen features: {missing_features[:20]}"
            )

        raw_known_amr_rows = len(Xall)
        if raw_known_amr_rows != 4233:
            log(
                f"[WARNING] expected 4233 raw known-AMR rows; "
                f"observed {raw_known_amr_rows}"
            )

        # Raw File04 can contain repeated Genome IDs outside the final 4,227-genome
        # development cohort. Do NOT fail or collapse before the development cohort
        # is identified. Only duplicates that survive into the locked development
        # cohort matter for reproducing FILE11C.
        raw_dup_counts = Xall[id_col].value_counts()
        raw_duplicate_ids = raw_dup_counts[raw_dup_counts > 1]
        raw_duplicate_id_count = int(len(raw_duplicate_ids))
        raw_duplicate_extra_rows = (
            int((raw_duplicate_ids - 1).sum()) if raw_duplicate_id_count else 0
        )

        if raw_duplicate_id_count:
            raw_examples = []
            for gid, count in raw_duplicate_ids.head(10).items():
                block = Xall.loc[Xall[id_col].eq(gid), feature_names]
                raw_examples.append(
                    {
                        "genome_id": gid,
                        "rows": int(count),
                        "unique_feature_vectors": int(block.drop_duplicates().shape[0]),
                    }
                )
            log(
                "[PROGRESS] raw known-AMR duplicates detected but deferred until "
                f"development subsetting | duplicate IDs={raw_duplicate_id_count} | "
                f"extra rows={raw_duplicate_extra_rows} | examples="
                + json.dumps(raw_examples, sort_keys=True)
            )

        manifest_header = pd.read_csv(inputs["local_manifest"], nrows=0)
        manifest_ids = likely_id_columns(list(manifest_header.columns))
        if not manifest_ids:
            raise RuntimeError("Cannot identify genome ID in local completion manifest.")
        manifest_id_col = manifest_ids[0]
        local_manifest = pd.read_csv(
            inputs["local_manifest"],
            dtype={manifest_id_col: str},
            low_memory=False,
        )
        local_ids = {
            norm_id(x)
            for x in local_manifest[manifest_id_col]
            if norm_id(x)
        }
        if len(local_ids) != EXPECTED_LOCAL_MANIFEST:
            raise RuntimeError(
                f"Expected 382 unique local-completion genomes, got {len(local_ids)}"
            )

        x_ids = set(Xall[id_col])
        if len(local_ids - x_ids):
            raise RuntimeError(
                f"{len(local_ids - x_ids)} local-manifest genomes absent from known-AMR matrix."
            )

        if args.development_labels is None:
            canonical = load_canonical_file07_common_cohort(root, x_ids)
        else:
            canonical = None

        if canonical is not None:
            labels, label_meta = canonical
            log(
                "[PROGRESS] using canonical File07 cohort directly | "
                "Genome ID + y + Phenotype cross-check + MLST"
            )
        else:
            labels, label_meta = discover_development_labels(
                root,
                x_ids,
                args.development_labels,
            )
        atomic_csv(
            outputs["label_audit"],
            pd.DataFrame(label_meta["audit"]),
        )

        dev_ids = labels["genome_id"].astype(str).tolist()
        dev_id_set = set(dev_ids)

        # Subset to the locked development cohort FIRST. Any raw duplicate that is
        # not part of the 4,227 development IDs is irrelevant to FILE11C training.
        Xdev_raw = Xall.loc[
            Xall[id_col].isin(dev_id_set),
            [id_col] + feature_names,
        ].copy()

        missing_dev_ids = sorted(dev_id_set - set(Xdev_raw[id_col]))
        if missing_dev_ids:
            raise RuntimeError(
                f"{len(missing_dev_ids)} development genomes are missing from "
                f"X_known_amr_final.csv. Examples: {missing_dev_ids[:20]}"
            )

        dev_dup_counts = Xdev_raw[id_col].value_counts()
        dev_duplicate_ids = dev_dup_counts[dev_dup_counts > 1]
        dev_duplicate_id_count = int(len(dev_duplicate_ids))
        dev_duplicate_extra_rows = (
            int((dev_duplicate_ids - 1).sum()) if dev_duplicate_id_count else 0
        )

        if dev_duplicate_id_count:
            inconsistent = []
            for gid, count in dev_duplicate_ids.items():
                block = Xdev_raw.loc[Xdev_raw[id_col].eq(gid), feature_names]
                unique_vectors = block.drop_duplicates().shape[0]
                if unique_vectors != 1:
                    ref = block.iloc[0]
                    differing_cols = block.columns[
                        block.ne(ref, axis=1).any(axis=0)
                    ].tolist()
                    inconsistent.append(
                        {
                            "genome_id": gid,
                            "rows": int(count),
                            "unique_feature_vectors": int(unique_vectors),
                            "differing_feature_columns": int(len(differing_cols)),
                            "example_differing_features": differing_cols[:20],
                        }
                    )

            if inconsistent:
                raise RuntimeError(
                    "NON-IDENTICAL duplicate Genome IDs remain INSIDE the locked "
                    "4,227-genome development cohort. Automatic collapse would change "
                    "the training matrix and is unsafe. Examples: "
                    + json.dumps(inconsistent[:10], sort_keys=True)
                )

            before = len(Xdev_raw)
            Xdev_raw = Xdev_raw.drop_duplicates(subset=[id_col], keep="first").copy()
            after = len(Xdev_raw)
            if before - after != dev_duplicate_extra_rows:
                raise RuntimeError(
                    "Development duplicate-collapse accounting mismatch: "
                    f"before={before}, after={after}, "
                    f"expected_removed={dev_duplicate_extra_rows}"
                )
            log(
                "[PROGRESS] collapsed exact duplicates INSIDE development cohort | "
                f"duplicate IDs={dev_duplicate_id_count} | "
                f"extra rows removed={dev_duplicate_extra_rows}"
            )

        if Xdev_raw[id_col].duplicated().any():
            raise RuntimeError(
                "Development genome IDs remain duplicated after exact-vector handling."
            )

        if Xdev_raw[id_col].nunique() != EXPECTED_DEV_N:
            raise RuntimeError(
                f"Development feature alignment has {Xdev_raw[id_col].nunique()} unique "
                f"genomes; expected {EXPECTED_DEV_N}."
            )

        Xidx = Xdev_raw.set_index(id_col)
        Xdev = Xidx.loc[dev_ids, feature_names].reset_index(drop=True).copy()
        y_dev = labels["label_binary"].to_numpy(dtype=np.uint8)
        source_local = np.asarray([gid in local_ids for gid in dev_ids], dtype=bool)

        n_local_dev = int(source_local.sum())
        n_ncbi_dev = int((~source_local).sum())
        if n_local_dev == 0 or n_ncbi_dev == 0:
            raise RuntimeError("Development source reconstruction produced an empty source class.")

        mlst_series = labels["MLST"].reset_index(drop=True) if "MLST" in labels.columns else None

        # Source/outcome confounding table.
        src_rows = []
        for source_name, mask in (
            ("local_amrfinder", source_local),
            ("ncbi_precomputed", ~source_local),
        ):
            yy = y_dev[mask]
            src_rows.append(
                {
                    "source": source_name,
                    "n": int(mask.sum()),
                    "R": int(yy.sum()),
                    "S": int(len(yy) - yy.sum()),
                    "R_prevalence": float(yy.mean()),
                }
            )

        a = int(np.sum(source_local & (y_dev == 1)))
        b = int(np.sum(source_local & (y_dev == 0)))
        c = int(np.sum((~source_local) & (y_dev == 1)))
        d = int(np.sum((~source_local) & (y_dev == 0)))
        source_outcome_or, source_outcome_p = fisher_exact(
            [[a, b], [c, d]],
            alternative="two-sided",
        )

        source_outcome = pd.DataFrame(src_rows)
        source_outcome["source_outcome_fisher_odds_ratio"] = float(source_outcome_or)
        source_outcome["source_outcome_fisher_p"] = float(source_outcome_p)
        source_outcome["caveat"] = (
            "Source assignment is non-randomized; association can reflect technical "
            "and/or population confounding."
        )
        atomic_csv(outputs["source_outcome"], source_outcome)

        log(
            f"[PROGRESS] development aligned | n={len(y_dev)} R={int(y_dev.sum())} "
            f"S={int((1-y_dev).sum())} | local={n_local_dev} ncbi={n_ncbi_dev}"
        )
        log(
            f"[PROGRESS] label source | {label_meta['selected_path']} | "
            f"id={label_meta['id_column']} | label={label_meta['label_column']} | "
            f"MLST={label_meta['mlst_column']}"
        )

        # ---------------------------------------------------------------------
        stage = "stage3_source_signature"
        log("Stage 3/8 — quantify source-feature signature and source-classifier CV")

        coefficients = pd.read_csv(inputs["file11c_coefficients"])
        source_assoc = source_feature_associations(
            Xdev,
            source_local,
            feature_names,
            coefficients,
        )
        atomic_csv(outputs["source_features"], source_assoc)

        source_markers = source_assoc.loc[
            source_assoc["primary_source_marker"], "feature"
        ].tolist()
        retained_features = [f for f in feature_names if f not in set(source_markers)]

        source_cv = source_classifier_cv(
            Xdev,
            source_local.astype(np.uint8),
            feature_names,
            mlst_series,
        )
        atomic_csv(outputs["source_cv"], source_cv)

        random_source_auc = float(
            source_cv.loc[
                source_cv["scheme"].eq("stratified_random_5fold"),
                "roc_auc",
            ].iloc[0]
        )

        log(
            f"[PROGRESS] source signature | primary markers={len(source_markers)} | "
            f"source-CV AUROC={random_source_auc:.4f}"
        )

        # Marker/model importance overlap table.
        overlap = source_assoc.copy()
        overlap["top50_abs_resistance_coefficient"] = False
        if overlap["abs_resistance_model_coefficient"].notna().any():
            top50 = set(
                overlap.nlargest(50, "abs_resistance_model_coefficient")["feature"]
            )
            overlap["top50_abs_resistance_coefficient"] = overlap["feature"].isin(top50)
        overlap["marker_and_top50_resistance_coef"] = (
            overlap["primary_source_marker"]
            & overlap["top50_abs_resistance_coefficient"]
        )
        atomic_csv(outputs["marker_overlap"], overlap)

        marker_top50_overlap = int(overlap["marker_and_top50_resistance_coef"].sum())

        # ---------------------------------------------------------------------
        stage = "stage4_full_model_reproduction"
        log("Stage 4/8 — reproduce full internal model and freeze sensitivity designs")

        Xdev_np = Xdev[feature_names].to_numpy(dtype=np.float64)
        fresh_full = new_outcome_model()
        fresh_full.fit(Xdev_np, y_dev)

        Xext = pd.read_csv(
            inputs["file11c_X_external"],
            dtype={"asm_acc": str},
            low_memory=False,
        )
        if "asm_acc" not in Xext.columns:
            raise RuntimeError("External 668-feature matrix lacks asm_acc.")
        if set(Xext["asm_acc"]) != set(pred_e2["asm_acc"]):
            raise RuntimeError("E2 matrix/prediction assembly sets differ.")
        Xext = (
            Xext.set_index("asm_acc")
            .loc[pred_e2["asm_acc"].astype(str), feature_names]
            .reset_index()
        )

        p_reproduced = positive_probability(
            fresh_full,
            Xext[feature_names].to_numpy(dtype=np.float64),
        )
        fresh_vs_frozen_max_abs = float(np.max(np.abs(p_reproduced - p_frozen)))
        fresh_vs_frozen_corr = float(np.corrcoef(p_reproduced, p_frozen)[0, 1])

        # Do not demand bitwise equality because solver/library serialization can vary.
        # But a large discrepancy means label reconstruction is not trustworthy.
        if fresh_vs_frozen_corr < 0.9999 or fresh_vs_frozen_max_abs > 0.01:
            raise RuntimeError(
                "Fresh full-model reproduction differs materially from frozen FILE11C "
                f"(corr={fresh_vs_frozen_corr:.6f}, max_abs={fresh_vs_frozen_max_abs:.6g}). "
                "Check development-label discovery."
            )

        design = {
            "script_version": VERSION,
            "created_utc": utc_now(),
            "analysis_class": "post-hoc exploratory source-shift sensitivity",
            "primary_FILE11C_result_modified": False,
            "E2_used_for_source_marker_definition": False,
            "E2_used_for_feature_selection": False,
            "E2_used_for_hyperparameter_selection": False,
            "E2_used_for_threshold_tuning": False,
            "all_pre_specified_sensitivity_models_reported": True,
            "source_marker_rule": {
                "BH_q_max": SOURCE_MARKER_Q,
                "absolute_prevalence_shift_min": SOURCE_MARKER_ABS_SHIFT,
                "defined_on": "development source labels only",
            },
            "outcome_model": {
                "estimator": "sklearn.linear_model.LogisticRegression",
                "C": MODEL_C,
                "solver": MODEL_SOLVER,
                "class_weight": None,
                "max_iter": MODEL_MAX_ITER,
                "random_state": MODEL_RANDOM_STATE,
                "threshold": THRESHOLD,
            },
            "sensitivity_models": {
                "frozen_original": "unchanged FILE11C probabilities",
                "source_debiased_full": (
                    "all development genomes; remove all primary source markers"
                ),
                "local_source_only": (
                    "local-AMRFinder development branch only; all 668 features"
                ),
                "ncbi_source_only": (
                    "NCBI-precomputed development branch only; all 668 features"
                ),
            },
            "genome_id_handling": (
                "All Genome ID columns are read as strings to preserve exact identifiers "
                "including trailing zeros after the decimal point."
            ),
            "source_causality_caveat": (
                "Source assignment is not randomized. Separability cannot by itself "
                "distinguish technical source effects from lineage/population/time confounding."
            ),
            "fresh_full_reproduction": {
                "external_probability_correlation_with_frozen": fresh_vs_frozen_corr,
                "external_probability_max_abs_difference": fresh_vs_frozen_max_abs,
            },
            "development_label_source": {
                "path": label_meta["selected_path"],
                "id_column": label_meta["id_column"],
                "label_column": label_meta["label_column"],
                "mlst_column": label_meta["mlst_column"],
            },
        }
        atomic_json(outputs["design"], design)

        log(
            f"[PROGRESS] full-model reproduction PASS | corr={fresh_vs_frozen_corr:.6f} "
            f"| max_abs={fresh_vs_frozen_max_abs:.3g}"
        )

        # ---------------------------------------------------------------------
        stage = "stage5_internal_sensitivity"
        log("Stage 5/8 — internal CV for pre-specified source sensitivity models")

        all_mask = np.ones(len(y_dev), dtype=bool)
        internal_rows = [
            internal_cv_model(
                Xdev,
                y_dev,
                retained_features,
                all_mask,
                "source_debiased_full",
            ),
            internal_cv_model(
                Xdev,
                y_dev,
                feature_names,
                source_local,
                "local_source_only",
            ),
            internal_cv_model(
                Xdev,
                y_dev,
                feature_names,
                ~source_local,
                "ncbi_source_only",
            ),
        ]
        internal_cv = pd.DataFrame(internal_rows)
        atomic_csv(outputs["internal_cv"], internal_cv)

        for row in internal_rows:
            log(
                f"[PROGRESS] internal {row['model']} | n={row['n']} | "
                f"AUROC={row.get('roc_auc', np.nan):.4f} | "
                f"BA={row.get('balanced_accuracy', np.nan):.4f}"
            )

        # ---------------------------------------------------------------------
        stage = "stage6_train_sensitivities"
        log("Stage 6/8 — train all sensitivity models using development data only")

        if len(retained_features) == 0:
            raise RuntimeError("Source-marker rule removed all 668 features.")

        models = {}

        debiased = new_outcome_model()
        debiased.fit(
            Xdev[retained_features].to_numpy(dtype=np.float64),
            y_dev,
        )
        models["source_debiased_full"] = (debiased, retained_features)

        local_model = new_outcome_model()
        local_model.fit(
            Xdev.loc[source_local, feature_names].to_numpy(dtype=np.float64),
            y_dev[source_local],
        )
        models["local_source_only"] = (local_model, feature_names)

        ncbi_model = new_outcome_model()
        ncbi_model.fit(
            Xdev.loc[~source_local, feature_names].to_numpy(dtype=np.float64),
            y_dev[~source_local],
        )
        models["ncbi_source_only"] = (ncbi_model, feature_names)

        log(
            f"[PROGRESS] models frozen | debiased_features={len(retained_features)} "
            f"| local_train={n_local_dev} | ncbi_train={n_ncbi_dev}"
        )

        # ---------------------------------------------------------------------
        stage = "stage7_external_sensitivity"
        log("Stage 7/8 — post-hoc E2 sensitivity scoring (no selection, no tuning)")

        method_scores = {"frozen_original": p_frozen}
        pred_table = pred_e2[
            [
                "asm_acc",
                "target_acc",
                "erd_group",
                "external_MLST",
                "lineage_novelty",
                "label_binary",
            ]
        ].copy()
        pred_table["frozen_original_probability_R"] = p_frozen
        pred_table["frozen_original_call"] = (p_frozen >= THRESHOLD).astype(np.uint8)

        metric_rows = [
            {
                "model": "frozen_original",
                "training_n": EXPECTED_DEV_N,
                "feature_count": EXPECTED_FEATURES,
                "training_source": "mixed_original_FILE11C",
                **frozen_metrics,
            }
        ]

        for name, (model, feats) in models.items():
            p = positive_probability(
                model,
                Xext[feats].to_numpy(dtype=np.float64),
            )
            method_scores[name] = p
            call = (p >= THRESHOLD).astype(np.uint8)
            pred_table[f"{name}_probability_R"] = p
            pred_table[f"{name}_call"] = call

            met = metric_bundle(y_e2, p, call)
            if name == "source_debiased_full":
                train_n = EXPECTED_DEV_N
                train_source = "mixed; source-marker features removed"
            elif name == "local_source_only":
                train_n = n_local_dev
                train_source = "local_amrfinder_only"
            else:
                train_n = n_ncbi_dev
                train_source = "ncbi_precomputed_only"

            metric_rows.append(
                {
                    "model": name,
                    "training_n": train_n,
                    "feature_count": len(feats),
                    "training_source": train_source,
                    **met,
                }
            )

        metrics_e2 = pd.DataFrame(metric_rows)
        atomic_csv(outputs["external_metrics"], metrics_e2)
        atomic_csv(outputs["external_predictions"], pred_table)

        for row in metric_rows:
            log(
                f"[PROGRESS] E2 {row['model']} | AUROC={row['roc_auc']:.4f} | "
                f"BA={row['balanced_accuracy']:.4f} | MCC={row['mcc']:.4f} | "
                f"Brier={row['brier']:.4f}"
            )

        boot = paired_cluster_bootstrap(
            pred_e2,
            method_scores,
            args.bootstrap_replicates,
            RANDOM_SEED,
        )
        atomic_csv(outputs["external_bootstrap"], boot)

        # ---------------------------------------------------------------------
        stage = "stage8_triage"
        log("Stage 8/8 — freeze go/no-go diagnostic summary")

        metric_idx = metrics_e2.set_index("model")

        deb_auc_delta = float(
            metric_idx.loc["source_debiased_full", "roc_auc"]
            - metric_idx.loc["frozen_original", "roc_auc"]
        )
        deb_ba_delta = float(
            metric_idx.loc["source_debiased_full", "balanced_accuracy"]
            - metric_idx.loc["frozen_original", "balanced_accuracy"]
        )
        local_auc_delta = float(
            metric_idx.loc["local_source_only", "roc_auc"]
            - metric_idx.loc["frozen_original", "roc_auc"]
        )
        local_ba_delta = float(
            metric_idx.loc["local_source_only", "balanced_accuracy"]
            - metric_idx.loc["frozen_original", "balanced_accuracy"]
        )

        def ci_for(model: str, metric: str) -> tuple[float | None, float | None]:
            q = boot[
                boot["model"].eq(model)
                & boot["metric"].eq(metric)
            ]
            if len(q) != 1:
                return None, None
            return (
                json_float(q.iloc[0]["ci95_low"]),
                json_float(q.iloc[0]["ci95_high"]),
            )

        deb_auc_ci = ci_for("source_debiased_full", "roc_auc")
        deb_ba_ci = ci_for("source_debiased_full", "balanced_accuracy")
        local_auc_ci = ci_for("local_source_only", "roc_auc")
        local_ba_ci = ci_for("local_source_only", "balanced_accuracy")

        # Operational compute-triage only; NOT a scientific significance rule.
        source_signature_strong = random_source_auc >= 0.80
        meaningful_point_rescue = max(
            deb_auc_delta,
            deb_ba_delta,
            local_auc_delta,
            local_ba_delta,
        ) >= 0.03

        positive_ci_rescue = any(
            lo is not None and lo > 0
            for lo, _hi in (
                deb_auc_ci,
                deb_ba_ci,
                local_auc_ci,
                local_ba_ci,
            )
        )

        if source_signature_strong and positive_ci_rescue:
            triage = "GO_STRONG_RERUN_HARMONIZED_AMRFINDER"
            rationale = (
                "Development source is strongly predictable and at least one "
                "pre-specified source sensitivity improves an E2 metric with paired "
                "cluster-bootstrap CI above zero. A fully harmonized development "
                "AMRFinder rerun is computationally justified."
            )
        elif source_signature_strong and meaningful_point_rescue:
            triage = "GO_PLAUSIBLE_RERUN_HARMONIZED_AMRFINDER"
            rationale = (
                "Development source is strongly predictable and at least one "
                "pre-specified sensitivity has >=0.03 point improvement, although "
                "paired uncertainty is not fully decisive. Harmonized rerun is plausible."
            )
        elif source_signature_strong:
            triage = "SOURCE_SHIFT_PRESENT_NO_CLEAR_E2_RESCUE"
            rationale = (
                "Feature source is strongly predictable, but pre-specified source "
                "sensitivities do not materially rescue E2. Source heterogeneity is "
                "a limitation but is unlikely to be the sole explanation."
            )
        else:
            triage = "NO_STRONG_SOURCE_SIGNATURE"
            rationale = (
                "The existing 668-feature vectors do not strongly encode source "
                "under the pre-specified classifier. A 4,227-genome harmonized rerun "
                "is lower priority."
            )

        top_source = source_assoc.head(20)[
            [
                "feature",
                "local_prevalence",
                "ncbi_prevalence",
                "absolute_prevalence_shift",
                "source_fisher_q_BH",
                "primary_source_marker",
                "resistance_model_coefficient",
                "coefficient_weighted_abs_source_shift",
            ]
        ].to_dict(orient="records")

        summary = {
            "script_version": VERSION,
            "status": "PASS_POSTHOC_SOURCE_SHIFT_DIAGNOSTIC",
            "completed_utc": utc_now(),
            "elapsed_seconds": time.time() - started,
            "analysis_class": "post-hoc exploratory source-shift sensitivity",
            "primary_FILE11C_result_unchanged": True,
            "frozen_prediction_sha256": csum["frozen_prediction_sha256"],
            "development": {
                "n": len(y_dev),
                "R": int(y_dev.sum()),
                "S": int((1 - y_dev).sum()),
                "local_amrfinder_n": n_local_dev,
                "ncbi_precomputed_n": n_ncbi_dev,
                "raw_known_amr_rows": raw_known_amr_rows,
                "raw_duplicate_genome_ids": raw_duplicate_id_count,
                "raw_duplicate_extra_rows": raw_duplicate_extra_rows,
                "development_duplicate_genome_ids_collapsed": dev_duplicate_id_count,
                "development_duplicate_extra_rows_removed": dev_duplicate_extra_rows,
                "duplicate_collapse_rule": (
                    "only exact 668-feature-vector duplicates surviving inside the "
                    "locked 4,227-genome development cohort"
                ),
                "label_source_path": label_meta["selected_path"],
            },
            "source_outcome_confounding": {
                "local_R_prevalence": float(y_dev[source_local].mean()),
                "ncbi_R_prevalence": float(y_dev[~source_local].mean()),
                "fisher_odds_ratio": float(source_outcome_or),
                "fisher_p": float(source_outcome_p),
                "causal_interpretation_allowed": False,
            },
            "source_signature": {
                "random_5fold_source_classifier_AUROC": random_source_auc,
                "primary_source_marker_count": len(source_markers),
                "retained_feature_count": len(retained_features),
                "source_markers_in_top50_abs_resistance_coefficients": marker_top50_overlap,
                "marker_q_threshold": SOURCE_MARKER_Q,
                "marker_abs_prevalence_shift_threshold": SOURCE_MARKER_ABS_SHIFT,
            },
            "full_model_reproduction": {
                "external_probability_correlation_with_frozen": fresh_vs_frozen_corr,
                "external_probability_max_abs_difference": fresh_vs_frozen_max_abs,
            },
            "external_sensitivity_point_deltas_vs_frozen": {
                "source_debiased_full_AUROC": deb_auc_delta,
                "source_debiased_full_balanced_accuracy": deb_ba_delta,
                "local_source_only_AUROC": local_auc_delta,
                "local_source_only_balanced_accuracy": local_ba_delta,
            },
            "external_sensitivity_paired_CI": {
                "source_debiased_full_AUROC": deb_auc_ci,
                "source_debiased_full_balanced_accuracy": deb_ba_ci,
                "local_source_only_AUROC": local_auc_ci,
                "local_source_only_balanced_accuracy": local_ba_ci,
            },
            "compute_triage": {
                "decision": triage,
                "rationale": rationale,
                "IMPORTANT": (
                    "Operational go/no-go for spending compute only. This is not a "
                    "confirmatory statistical decision and does not replace FILE11C."
                ),
            },
            "top_source_associated_features": top_source,
            "guardrails": {
                "E2_used_for_source_marker_definition": False,
                "E2_used_for_feature_selection": False,
                "E2_used_for_hyperparameter_selection": False,
                "E2_used_for_threshold_tuning": False,
                "all_pre_specified_sensitivity_models_reported": True,
                "source_debiased_result_is_posthoc": True,
                "source_only_models_are_posthoc": True,
                "new_primary_external_claim_allowed": False,
            },
            "outputs": {
                k: str(v.relative_to(root))
                for k, v in outputs.items()
            },
        }
        atomic_json(final_summary_path, summary)
        failure_path.unlink(missing_ok=True)

        log("=" * 112)
        log("FILE11F STATUS : PASS_POSTHOC_SOURCE_SHIFT_DIAGNOSTIC")
        log(f"Source CV AUROC           : {random_source_auc:.4f}")
        log(f"Primary source markers    : {len(source_markers)}/{EXPECTED_FEATURES}")
        log(f"Markers in top-|coef| 50  : {marker_top50_overlap}")
        log(
            f"Debiased E2               : AUROC={metric_idx.loc['source_debiased_full','roc_auc']:.4f} "
            f"(delta={deb_auc_delta:+.4f}) | "
            f"BA={metric_idx.loc['source_debiased_full','balanced_accuracy']:.4f} "
            f"(delta={deb_ba_delta:+.4f})"
        )
        log(
            f"Local-source-only E2      : AUROC={metric_idx.loc['local_source_only','roc_auc']:.4f} "
            f"(delta={local_auc_delta:+.4f}) | "
            f"BA={metric_idx.loc['local_source_only','balanced_accuracy']:.4f} "
            f"(delta={local_ba_delta:+.4f})"
        )
        log(f"COMPUTE TRIAGE            : {triage}")
        log(f"Final summary             : {final_summary_path}")
        log("=" * 112)
        return 0

    except KeyboardInterrupt:
        atomic_json(
            failure_path,
            {
                "script_version": VERSION,
                "status": "INTERRUPTED",
                "stage": stage,
                "utc": utc_now(),
                "message": "Frozen FILE11C artifacts remain unchanged.",
            },
        )
        log("FILE11F INTERRUPTED. Frozen FILE11C artifacts remain unchanged.")
        return 130

    except Exception as exc:
        atomic_json(
            failure_path,
            {
                "script_version": VERSION,
                "status": "FAILED",
                "stage": stage,
                "utc": utc_now(),
                "error_type": type(exc).__name__,
                "error": str(exc),
                "traceback": traceback.format_exc(),
            },
        )
        log("")
        log("FILE11F FAILED")
        log(f"Stage : {stage}")
        log(f"Error : {exc}")
        log(f"Crash record: {failure_path}")
        return 1

    finally:
        lock_path.unlink(missing_ok=True)


if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    raise SystemExit(main())
